### ISSUE TITLE
server not found 

### ISSUE THREAD

**Issue by hassanmurtaxa** [tinode/chat#10]
server not found after running in dockerized environment .

localhost:6060
gives : 404 not found

**Comment by or-else** [comment]
It's hard for me to diagnose the problem based on your description. I assume you are trying to connect the web app to the server running in a container. Apparently the server is not exposed on the local host at the expected port.

**Comment by hassanmurtaxa** [comment]
My bad, I should have explained a bit more.

Images will explain everything clearly. Since both things are working in dockerized environment perfectly and I've followed the steps given by you but still I'm facing a problem. 

Please have a look:

![selection_001](https://cloud.githubusercontent.com/assets/18144993/25217566/d884a786-25c0-11e7-8ad2-b82f61c14b7a.png)
![selection_003](https://cloud.githubusercontent.com/assets/18144993/25217567/d8b2bbee-25c0-11e7-9f6b-3a1170478939.png)

**Comment by or-else** [comment]
Thanks for the clarification. It looks like everything is actually fine and works as expected, except I forgot to update the installation doc.
 
404 means the server is up and running but the samples/chatdemo.html is not found. It's not found because I removed it a while ago as no longer relevant. Please try http://localhost:6060/x/example-react-js/index.html instead. I've updated the doc to point to the correct file. Thanks!

example-react-js/index.html by default connects to api.tinode.co. Search for api.tinode.co in index.html and replace it with localhost:6060

**Comment by hassanmurtaxa** [comment]
Thank you for your previous responses.

I seriously don't know what's the issue but I'm still not able to run it.  

Do I have to download files such as example-react-js & tinode master js? and place it in /home/username(in my case hassan)/ tinode/example-react-js ?

I changed the host to "localhost:6060" still problem persist.

BTW I did this too but still 404 page not found.

**Comment by or-else** [comment]
I'll look into in on Monday.

**Comment by hassanmurtaxa** [comment]
Sure, I'm waiting.

**Comment by or-else** [comment]
OK, I've updated the dockerfile. The 404 was due to missing static files. They did not get included into the container. The server ran fine but could not find the files to serve. Please rebuild the container from the file provided.
That said, one problem remains - the demo app will try to connect to api.tinode.co, not your dockerized server. I'll update that later today or tomorrow.

**Comment by or-else** [comment]
The demo app is at http://localhost:6060/x/

**Comment by or-else** [comment]
All fixed, should work now.  The demo app is at http://localhost:6060/x/

**Comment by or-else** [comment]
I assume everything is fine, closing the issue.
