### ISSUE TITLE
Chatbot.py disconnection

### ISSUE THREAD

**Issue by admill1519** [tinode/chat#114]
### Subject of the issue
chatbot.py keeps getting disconnect on receiving large images and sometimes on text messages. I am handling it with try and except but its not working. is there any better solution for this. And it does not refresh or restart itself on error.

### Is this a bug report of a feature request?
I am reporting here bug as well as requesting a new feature

### Your environment
- [ ] api.tinode.co
- [x] Your own setup:
  * platform = Ubuntu
  * version of tinode server
  * database backend = MySQL
  * which client used (javascript, android, cli) and its version

### Steps to reproduce
Send any large file and it will produce the error

### Expected behaviour
If not able to handle text or image it should go in the exception and should not disconnect the bot.
Right now on every error bot is going offline

### Actual behaviour
if any error occurs it goes in exception but still bot goes offline

### Server-side log
"Disconnect:" error message captured by exception
### Client-side log
Copy client-side log here. You may also attach it to the issue as a Dfile.

**Comment by or-else** [comment]
I cannot reproduce. Please fill out the but report form completely. It asks these questions because I need then answered in order to reproduce the bug you are reporting. 

Have you modified the chatbot.py in any way? Are you trying to read the message in the chatbot? If so, have you seen the discussion here: https://github.com/tinode/chat/issues/111?
