### ISSUE TITLE
How to get delete permission 

### ISSUE THREAD

**Issue by rjliulei** [tinode/chat#121]
How to get delete permission ? I tried {set} ,but not useful.

**Comment by rjliulei** [comment]
if I do hard delete message,only I can receive {pres} message,the other do not receive {pre}.Is this nomal?

**Comment by rjliulei** [comment]
What does this mean?
"User can soft-delete or hard-delete messages what="msg". Soft-deleting messages hides them from the requesting user but does not delete them from storage. An R permission is required to soft-delete messages hard=false (default). Messages can be deleted in bulk by sepcifying one or more message ID ranges in delseq parameter. Hard-deleting messages deletes them from storage affecting all users. ### **The D permission is needed to hard-delete messages.**"
![360 16620621757993](https://user-images.githubusercontent.com/6119104/42405688-e1d7eef6-81cc-11e8-9000-cf00b2a1c2ec.png)

**Comment by or-else** [comment]
> 1.If I do hard delete message,only I can receive {pres} message,the other do not receive {pres}.Is this nomal?

If that happens when you indeed hard delete a message then it's a bug, but I don't think you are hard-deleting a message. What most likely is happening is that you are requesting to hard-delete a message but don't have a `D` permission. The server silently converts your hard-delete to soft-delete and notifies just you that the message was deleted for you.

>2.If I want to delete messages for everybody,what need I do?

Send a `{del hard=true}` and have a `D` permission.

> 3. When I set {sub.mode} to "JRWPAD",I get "JRWPA" every time.why?
 
In the first case you are trying to (a) set default permissions on a P2P topic and separately (b) set a GIVEN permission for the other user. For (a) you get the first 403 "permission denied" because the operation makes no sense. For (b) you successfully change the GIVEN permission of the other user (200 OK) then maybe confusingly the server reports back your own permissions instead of the changed permission of the other user. 

In the second case you just do (b) alone and you get the same response as described above. 

Currently there is no way for a user to gain a `D` permission in a P2P topic:
https://github.com/tinode/chat/blob/master/server/topic.go#L853
It's a product decision. It seems to be OK to allow a user to hard-delete his own messages (and maybe it should be added as a configurable option) but certainly not OK to allow one user to hard-delete any message in a P2P conversation.

**Comment by rjliulei** [comment]
En...Yes，the problem occured on a P2P topic。I think allowing a user to hard-delete his own messages is necessary.I.e, I want to revoke my message,Is there any solution?

**Comment by or-else** [comment]
Right now - no solution. It needs to be added as a feature. It's actually quite easy to add.

**Comment by rjliulei** [comment]
OK,hope it coming soon!
