### ISSUE TITLE
How trivial would it be to implement another database store

### ISSUE THREAD

**Issue by tonyalaribe** [tinode/chat#13]
Hello, 

How trivial would it be to implement another database store. My use case would involve a  lot of traffic, so being able to use a database like redis or cassandra would be quite beneficial.

How trivial would it be to implement redis support, while taking advantage of features like redis pub-sub, which are important for an application such as this? Is this something I can tackle and create a pull request for without refactoring the entire application? (Bear in mind, I haven't gone through the code indept) .

EDIT: 
ON more thought. Having the messages stored in a Cassandra database, and the meta data stored in Postgres, is the ideal scenario for me. Would this be possible?

**Comment by or-else** [comment]
Hi Tony,

On your first question of implementing a new DB backend: yes, it's quite straightforward. The new DB backend just needs to implement the following interface: https://github.com/tinode/chat/blob/master/server/store/adapter/adapter.go
Take a look here for a sample implementation: https://github.com/tinode/chat/blob/master/server/db/rethinkdb/adapter.go

I don't think it matters if you use a single backend, like MySQL or a mixed one (Cassandra + Postgres). You just write an appropriate adapter.

Regarding Redis, I would not advise it because it's really not a persistent store. It's rather an in-memory DB with snapshotting for persistence. But it's really up to you.

**Comment by or-else** [comment]
Given that there are no followup questions, I assume your received a satisfactory answer. I'll close the issue. Feel free to reopen if you have more questions.

**Comment by SantoshSah** [comment]
@tonyalaribe , have you implemented new data adaptor for Cassandra and Postgres?
