### ISSUE TITLE
Authentication scheme

### ISSUE THREAD

**Issue by bogdantarasenkozp** [tinode/chat#146]
Hi, i am trying to use token authentication scheme but it doesnt works, also i tried to find some more info about this but i can't, is this a bug or maybe i made some mistake?

**Comment by or-else** [comment]
Please describe the issue in detail. Thanks.
There are no known bugs in authentication.

**Comment by or-else** [comment]
Ideally, please file the default issue template.

**Comment by bogdantarasenkozp** [comment]
Is this a bug or this functionality is not finished yet?

**Comment by or-else** [comment]
You are sending an invalid packet. `"login": "false"` is invalid because `"login"` is expected to be a boolean, not a string. You are sending a string.

Even if you fix this issue you are still doing something which does not make sense to me. You cannot create an account with a `token` authentication because the client is not expected to be able to generate tokens. At least not the same tokens which are currently implemented.
