### ISSUE TITLE
DialogFlow Chatbot

### ISSUE THREAD

**Issue by fstn** [tinode/chat#169]
### Subject of the issue
The idea is to code a chatbot that send messages to [dialogflow](https://dialogflow.com/) and reply to the user.

## Solution1
I can add a new folder here: https://github.com/tinode/chat/tree/master/chatbot
I'll develop it using NodeJS

I'll modify he docker file to add node support and be able to add PLUGIN_DIALOGFLOW_CHAT_BOT_ENABLED=true 
PLUGIN_DIALOGFLOW_KEY=....
 PLUGIN_DIALOGFLOW_PROJECTID=...

## I do an other standalone project

I create a new NodeJS project.
Users have to run the project to enable the bot.

### Is this a bug report of a feature request?
- [ ] Bug report
- [x] Feature request

**Comment by or-else** [comment]
Sure. 

It would be nice to make it docker-compatible with the python bot. I.e. instead of requiring the new variable `PLUGIN_DIALOGFLOW_CHAT_BOT_ENABLED` let's rename the existing `PLUGIN_PYTHON_CHAT_BOT_ENABLED` to just `PLUGIN_CHAT_BOT_ENABLED` and ensure that either docker container can be used. 

The bot-specific parameters should go to the specific docker. In other words PLUGIN_DIALOGFLOW_KEY=....
PLUGIN_DIALOGFLOW_PROJECTID=...
should be parameters for the dialogflow-bot docker image.

It's highly unlikely that anyone would want to use multiple chatbots at the same time, so need to run multiple bot containers at the same time.

**Comment by or-else** [comment]
I assume this is not happening. Even if it does there is no point in keeping this issue open. Closing.
