### ISSUE TITLE
Add new users to database from json file

### ISSUE THREAD

**Issue by mohgh** [tinode/chat#202]
### Subject of the issue
Sorry if it's already described in the docs. I've searched for it and I couldn't find my way around this issue. How can I add new users (from a JSON file for example) into an already created database? Can I use db-init utility or should I use cli tool? How can I create a root user and what are the commands in cli for adding users?
### Is this a bug report of a feature request?
- [ ] Bug report
- [x] Feature request

**Comment by or-else** [comment]
There are three ways to create accounts:

* A user can register through the client-side UI. 
* A user can be created manually by an admin using `tn-cli` (`acc` command)
* If the user already exists in an external database, the Tinode account can be automatically created on the first login using the `rest` authenticator.

You cannot currently use `init-db` to add users to a live database because it resets the database first. Although it's not too difficult to modify init-db for adding new accounts I would rather keep things simple and suggest using `tn-cli` or `rest-auth`.

**Comment by or-else** [comment]
No, you don't need a root user for creating accounts in tn-cli. But if you want one see here:
https://github.com/tinode/chat/blob/devel/docs/faq.md

**Comment by or-else** [comment]
The commands are described in tn-cli. Type `<command> -h`

**Comment by mohgh** [comment]
Can you please help me to edit `db-init` program to bulk add users from a JSON file? 
Is commenting below lines are enough in `gendb.go` file (lines 34-42)?
```

} else {
		log.Println("Database exists, DB version is correct. All done.", store.GetAdapterName())
		//return
	}

	//err = store.InitDb(config, true)
	//if err != nil {
	//	log.Fatal("Failed to init DB:", err)
	//}
```

**Comment by or-else** [comment]
Yes, looks correct.

**Comment by mohgh** [comment]
Thank you, I'm closing this issue. But FYI the acc command in cli is not working properly. No Id is added to user and tags are added malformed.

**Comment by or-else** [comment]
> acc command in cli is not working properly. No Id is added to user and tags are added malformed.

Could you please open a new issue for this?

**Comment by or-else** [comment]
I just tested `tn-cli acc` and it worked just fine:
```
tn-cli> acc --uname=test --password=test123  --tags=test,test_user --fn=Test_User --cred=email:gene+test@tinode.co  
201 created 
```
