### ISSUE TITLE
Add support for voice and video messages

### ISSUE THREAD

**Issue by Frederic-Zhou** [tinode/chat#237]
I tested “Tinode” for a few days. this is the one of the best of the open source IM I have ever seen

and，I have a small suggestion:

**Can the Tinode support send voice messages in the future?**

All most well-know IM app supported the voice messages. 

Many users prefer to send voice messages on mobile devices compared to text messages.

**Comment by or-else** [comment]
I certainly want to add features to the product but it has to wait until more contributors join us or until we get more time. We are currently busy with the iOS client: https://github.com/tinode/ios/commits/drafty

Otherwise sure, voice calling and voice messaging is a useful feature, I would like it to be a part of Tinode.

See also https://github.com/tinode/chat/issues/150

**Comment by or-else** [comment]
Voice messages will be in the next release.

**Comment by or-else** [comment]
Voice messages released in 0.19.0

**Comment by or-else** [comment]
Video messages are not yet done. Please do not close.

**Comment by or-else** [comment]
Audio messages released, video messages moved to a separate issue #821.

**Comment by crendy** [comment]
The mobile web version does not yet support voice messaging
@or-else

**Comment by or-else** [comment]
@crendy: Your statement is incorrect. If you believe otherwise, please file a bug report.
