### ISSUE TITLE
Not enough data in push notification plugin

### ISSUE THREAD

**Issue by jetmind** [tinode/chat#368]
I'm implementing my own push notifications plugin. In order to format message I need to get topic's public info so that I can show the name of a group chat in the notification message, but it seems like there is no way of doing that without modifying the core to pass more info to the plugin. Payload only contains topic name and no additional data. 

Am I missing something? If not, is this something you'll be interested in adding to the core?

**Comment by or-else** [comment]
This is by design. The logic behind this decision is to avoid duplication of traffic.

If you receive a push for a known topic you already have its `public`. If topic is unknown then you should fetch this data from the server. Look at the current Android implementation of this logic:
https://github.com/tinode/tindroid/blob/master/app/src/main/java/co/tinode/tindroid/fcm/FBaseMessagingService.java#L96

If your use case is different from the one described above, please tell me more about it.

**Comment by or-else** [comment]
Do you have further questions? Are you satisfied with the answer?

**Comment by or-else** [comment]
No followup in a week. Let's consider this resolved.
