### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by tgt5248** [tinode/chat#466]
### -  Feature request

I am writing down the function that our team want to add while using tinode.  Our team used the tinode iOS version.

1. Find friends by ID and phone number
I think it is inconvenient to find a friend with the user code.

2. Change user code to copyable
When I added a friend, I experienced inconvenience because the user code was not copied. I hope the user code can be copied.

3. Segmentation of sending files, such as videos and voice messages
Currently, tinode is categorized as sending image files and sending files. user can send videos, documents, and voice messages from Send File, but I think it's convenient to classify each item.

4. Description of the error code
When an error code appears, only the code number is displayed and the error is not known. In this case, I want to know in detail what kind of error.

5. Synchronize phonebook
I would like to add friends automatically when the user using tinode is in the phone book.

6. Voice Talk Features

7. Video chat function

8. Add a birthday
I want to add a birthday to my profile so others can see it.

9.Add Chatbot Function to iOS/ Android

10. Add Emojis or stickers

Thanks!

**Comment by or-else** [comment]
> 1. Find friends by ID and phone number

This is probably better if implemented on the server side. We do want this fixed, but it's a bit involved because of phone number complexities. We will work on this on the server side afer finishing the refactoring of clustering.

> 2. Change user code to copyable

Not sure what you mean but you are welcome to send a pull request.

> 3. Video and audio attachments

This is a client-side feature. It has been discussed numerous times. You are welcome to take a shot at it. Here are a couple of conversation on the same subject:
https://groups.google.com/forum/?#!topic/tinode/72dJPN71vfA
https://groups.google.com/d/msg/tinode/1tEmVsRcT3Q/Z9S65PwjEQAJ

> 4. Description of the error code

I'm not sure what you mean. Please elaborate. Maybe give an example.

> 5. Synchronize phonebook

You are welcome to send a pull request.

> 6. 7. Live voice and video

These are very large projects.

> 8. Birthday

This is quite trivial to add. The personal information is stored in `vcard`:
https://github.com/tinode/chat/blob/master/docs/API.md#public
The birthday field is defined as `bday` (https://en.wikipedia.org/wiki/VCard), so use something like `bday: "2001-01-03"` to store and transmit birthdays, no server-side changes are needed.

> 9. Add Chatbot Function to iOS/ Android

Chatbot is a server-side feature and it already exists. Not sure what you find missing.

**Comment by pwFoo** [comment]
Audio / Video feature (peer to peer) could be done with a javascript library
https://github.com/feross/simple-peer

#150

**Comment by or-else** [comment]
> Audio / Video feature (peer to peer) could be done with a javascript library

It should be implemented on all platforms: iOS, Android, web.

**Comment by or-else** [comment]
There was no update on this for a while. The requested clarifications of the feature requests were not provided. Other feature requests (audio, video) were covered elsewhere. Closing.
