### ISSUE TITLE
[Ask About Tinode ACS]

### ISSUE THREAD

**Issue by riandyrn** [tinode/chat#48]
Hello, Gene

I have question regarding Tinode ACS.

So I'm still not fully understand why would we need both `ModeWant` & `ModeGiven` when defining user access to the topic. Shouldn’t be `ModeGiven` only is enough to define it?😅 

I mean `ModeWant` is only useful when user want to mute the conversation, right? But for the most of the use cases, `ModeGiven` should be enough, right?

For example when group owner want to promote a member to become admin, it would give the member `"AS"` permissions. Naturally, user would become admin directly. 

But since there is a user's `ModeWant`, user need to elevate itself to admin first before it able to become the admin (set its `ModeWant` to also include `"AS"`). So why must we take this two steps when just once should be enough?

Maybe there is a design consideration behind this implementation?

Thanks

**Comment by or-else** [comment]
Hi Riandy,

ModeWant has two purposes:

1. Filtering.
The following ModeWant is useful: `J`,`P`, `A`. No `want-J` means user does not want to be invited to the topic, i.e. filtering out spammy topics.  No `want-P` means the user does not want to see notifications from the topic, i.e. muting topics. No `want-A` means the user does not want to do admin tasks, like approve requests: a user may not be willing to do it because its a chore.

2. Requesting new permissions.
ModeWant is used to request new permissions. For instance, the user does not have an `R` permission. The user sets `want-R` as a way to request the `R` permission from the topic admin.

I understand that it seems complex, but I don't see how to simplify it.
