### ISSUE TITLE
Synchronize Phonebook with Chat

### ISSUE THREAD

**Issue by alttutar** [tinode/chat#486]
I think this is a good feature to add. I would love to work on this, and if someone is also interested, let's keep in touch.

**Comment by or-else** [comment]
Phone book sync is mostly a client-side feature and it's been implemented on both iOS or Android. What exactly do you have in mind? Please elaborate. Thanks.

**Comment by alttutar** [comment]
Upss I looked into a feature request from May 27th, and it seems like it has been outdated. Another feature that I can give it a shot for. Thanks!

**Comment by or-else** [comment]
What platform would like to work on? Server - Go, clients - Java, Javascript, Swift.

**Comment by alttutar** [comment]
I would prefer working on the server with Go or the Swift client!

**Comment by or-else** [comment]
@aforge Hey, do you have a starter project in the iOS client?

**Comment by or-else** [comment]
Re: server. Would you like to work on a PostgreSQL adapter?

**Comment by alttutar** [comment]
PostgreSQL adapter sounds good to me! Let me know where I could start.

**Comment by or-else** [comment]
Here is the relevant conversation on PgSQL: #232

@a9u has started working on it in October last year #300 but she apparently did not have time and PR did not progress much. You are welcome to continue where she left off or start anew (which maybe a better idea because the original MySQL adapter has changed since then).

It's not that complex, maybe a week of part time work. Please comment on the original issue #232 if you have questions.

Thanks!

**Comment by alttutar** [comment]
Thanks! I will start working on that.

**Comment by aforge** [comment]
As for [Tinodios](https://github.com/tinode/ios), if you also prefer you can help
with either https://github.com/tinode/ios/issues/158 or https://github.com/tinode/ios/issues/157.
The former is a UI problem. The latter is a clear bug and has a higher priority.
