### ISSUE TITLE
[Issues on Push Message]

### ISSUE THREAD

**Issue by riandyrn** [tinode/chat#50]
Hello, Gene

Currently I’m facing several problems when trying to implement following push message use cases in client app:
1. FCM token refresh in the middle of user session
2. User logout in app

So as far as I understand, it is possible for FCM token to be refreshed. When this event occurs, we need to update our existing token on the server.

Yet in Tinode, FCM token (called `"deviceId"` in Tinode) could only be updated in `{hi}`. So in case of token refresh occurs in the middle of user session, we need to break the session first to register new updated token. 

So maybe there is a better way to do this which I'm missing?

The next issue occurs when single device is being used by multiple user. So for example User A & User B use single device together.

In Tinode, `deviceId` is associated with `uid` [(link)](https://github.com/tinode/chat/blob/devel/server/store/store.go#L430-L432), yet `store.Devices.Delete()` is only called when `deviceId` is invalid [(link)](https://github.com/tinode/chat/blob/devel/push_fcm/push_fcm.go#L150).

Since User A & User B use the device together, then the `deviceId` would be same for them. So in case User A has been logout & User B logged in, then message for User A would be still delivered to User B. 

So I think it's better if we also offers delete device functionality for user so the client could notify server which `deviceId` still used for certain user & which is not.

What do you think?

---

Also if I may suggest I think it's better if we differentiate between `deviceId` & fcm token though. The reason is because essentialy a device may have multiple tokens due to rotation / refresh. 

Since basically `store.Devices.Update()` is defined as "upsert", then every unused fcm token would be just pile up on database. But if we differentiate between `deviceId` & fcm token then we could just update the associated token for the `deviceId` leaving more compact space on the database.

What do you think?

Thanks

**Comment by or-else** [comment]
Hi Riandy,

> FCM token refresh in the middle of user session

Yes, it's an oversight. This functionality is needed but missing. I see two options: allow `{hi}` in the middle of the session or create a new packet for the purpose, like `{dev}`. Let me look at the code and I'll suggest which one is more suitable.

> User logout in app

So, if I understand correctly, when user logs out from the device, the app needs a way to tell the server to invalidate the token. But maybe it's not needed. Since tokens are stored by UID, if the same token is used with a new UID the server can detect that and then invalidate the token for the old UID. I think the automatic token invalidation is better than explicit because it will not allow a malicious client to intentionally receive pushes for a different user. If you don't see problems with this approach, I'll add automatic token deletion on the server.

> Also if I may suggest I think it's better if we differentiate between deviceId & fcm token though. The reason is because essentialy a device may have multiple tokens due to rotation / refresh.

But what is `deviceId` then? I don't think there is a need for a `deviceId` separate from the push token. Just think of `deviceId` as a different name for the token. 
As for stale deviceId (or token), I think it needs garbage collection - automatically delete deviceId/token after a month of two of inactivity.

**Comment by riandyrn** [comment]
> I think the automatic token invalidation is better than explicit because it will not allow a malicious client to intentionally receive pushes for a different user.

Yeah, you’re right it’s much better (y). 

Maybe the trade off is when user already logged out then move to new device, they would still receive the notification in the old device. Maybe you have suggestion regarding this case?

> But what is deviceId then?

I was thinking to use [InstanceID](https://developers.google.com/instance-id/)

**Comment by or-else** [comment]
> Maybe the trade off is when user already logged out then move to new device, they would still receive the notification in the old device. Maybe you have suggestion regarding this case?

I'm thinking about adding a way of updating the token which should cover both cases: 
1. Replace old token with the new token
2. Replace token with null

> I was thinking to use InstanceID

It's not going to be used on the backend so I would rather not collect it.

**Comment by or-else** [comment]
I think allowing {hi} in the middle of a session is the simplest solution: https://github.com/tinode/chat/pull/51

**Comment by riandyrn** [comment]
Hello, Gene

Yeah, it’s awesome 👍 

I have a little bit fix for null params in `{hi}` response though: https://github.com/tinode/chat/pull/55

Thanks
