### ISSUE TITLE
Readme section on XMPP is not correct

### ISSUE THREAD

**Issue by stevenroose** [tinode/chat#558]
It says

> Tinode is not XMPP/Jabber. It is not compatible with XMPP. It's meant as a replacement for XMPP. On the surface, it's a lot like open source WhatsApp or Telegram.

However XMPP is not a "Instant messaging platform" or "Instant message server" like Tinode is described as. XMPP is a federation protocol. It's a language and set of conventions.

What you're saying is equivalent to "Firefox is not HTTP, it's meant as a replacement to HTTP.".

What you probably want to say is "Tinode doesn't federate over XMPP.".

**Comment by or-else** [comment]
XMPP is a messaging protocol with an optional federation feature. Tinode is also a messaging protocol (as well as a server and several clients which implement said protocol). I think the current wording causes very little confusion. Your proposed wording would imply that Tinode just does not use XMPP for federation but otherwise XMPP-compatible.

**Comment by gilons** [comment]
`https://www.lowendtalk.com/discussion/11105/tutorial-set-up-a-federated-xmpp-chat-network-with-ejabberd-your-own-google-talk`
Ejjabberd an erlang xmpp server is able to implement SS fedearation. see the link above to know more

**Comment by or-else** [comment]
Is there anything else to be discussed here? New angles?

**Comment by stevenroose** [comment]
> XMPP is a messaging protocol with an optional federation feature. Tinode is also a messaging protocol (as well as a server and several clients which implement said protocol). I think the current wording causes very little confusion. Your proposed wording would imply that Tinode just does not use XMPP for federation but otherwise XMPP-compatible.

You're right that XMPP is a c2s and s2s protocol and that one can in principle use it just c2s without federation. But in common terms, saying "compatible with XMPP" implies federating, though interpretation is ofc debatable. "It's meant as a replacement for XMPP." does very much suggest Tinode does have an s2s layer, though. Which I find misleading at best.

Leaving the documentation for what it is, has it ever been considered to support XMPP federation?

**Comment by or-else** [comment]
The phrases "Tinode is not XMPP/Jabber. It is not compatible with XMPP. It's meant as a replacement for XMPP." are not meant to list all possible features/differences between Tinode and XMPP. I don't think anyone reading "It's meant as a replacement for XMPP" would think that it's feature-by-feature the same as XMPP. 

If you feel strongly, please propose an alternative wording.

> has it ever been considered to support XMPP federation?

Yes, it has been considered. We are not going to support XMPP federation because XMPP federation is unusable. We do want federation but we want it done right. It's in the list of planned features.

**Comment by stevenroose** [comment]
> We do want federation but we want it done right.

That sounds an awefule lot like [xkcd 927](https://xkcd.com/927/) to me though :+1: 

What are your concrete issues with the XMPP federation protocol? It's so incredibly flexible, using it doesn't mean that you have to be adding all Jabber (the XMPP chat network) features to it, but you can define Tinode-specific extensions but still use the core protocol which has had 20 years of iterations and improvements. Adding Jabber-compatibility could be afterwards done as a community effort, perhaps.

But to be entirely honest, reinventing the wheel is not going to add much value to the ecosystem of chat software. Matrix did that 5 years ago, Wire started last year. This is only causing more splintering. XMPP is not perfect, especially not the existing feature set built on it. But the elegancy of XMPP makes that all that is optional. You're free to ignore extensions that don't make sense and develop and propose new standard extensions that you think do make sense.

**Comment by or-else** [comment]
> That sounds an awefule lot like xkcd 927 to me though 👍

Wow! You are accessing this "Internetes" thing from a UNIVAC using a dial-up modem with an acoustic coupling? Amazing!  Are FLOW-MATIC developers still in demand?

> What are your concrete issues with the XMPP federation protocol?

The main problem is that the fanout happens at the origin.

>  It's so incredibly flexible

That is another problem. Enabling extensions was a mistake.

> had 20 years of iterations and improvements

And got nowhere. I believe XMPP should be buried. In the next 5 years someone will come out with a better protocol and it will take over the world.

**Comment by stevenroose** [comment]
Well, it seems we won't get along. Good luck implementing federation. I hope you're right about your last statement, though: some chat federation protocol to take over the world. We desperately need one.

**Comment by GwynethLlewelyn** [comment]
What we need is a port of ejabberd to Go :-) How exactly the nitty-gritty details are implemented should be somewhere way up the abstraction layers. If you hate XMPP, fine; use Yet-Another-Messaging-Protocol-I-Came-Up-This-Morning-Before-Coffee, if that's what rocks your boat. However, keep in mind that there are good reasons why XMPP is still around, after two decades of development. And ejabberd's parent company didn't go bankrupt; they just cleverly extended their messaging server to be compatible with other protocols, namely, MQTT. So, instead of inventing their own protocol, ProcessOne just makes their own server software compatible with more and more protocols (I understand that ejabberd is modular in that regard; it's been, well, 20 years since I last looked at it, and I don't know Erlang in any case).

Remember Google Chat? It started being implemented on top of XMPP, with the promise of joining existing federations — which they even managed to do with a few selected networks. It was seen as a 'killer app' to Microsoft's own Message (Facebook's was 'not there yet'), mostly because it could _interoperate_ with other (independent) networks; and, conversely, if you had a Gmail account, you had a unique Jabber ID for any XMPP-speaking server out there.

That was the theory. A couple of years after the launch, Google 'decided' that, after all, they hated XMPP, and came up with their own proprietary protocol. They lost a huge chunk of their chat users shortly afterwards; they simply couldn't keep up with the demands on new goodies that the competition was introducing at a neckbreaking pace; and it was a 'minor' project anyway. They still tried to incorporate it into Google Docs; then on Hangouts; and it's still somewhere. In fact, several instances of 'chatting software' exist, depending on the current tool you're using. They're also all incompatible with each other (so, messages left on a chat on, say, a Google AppScript app, will _not_ show up on Gmail, and so forth) — exactly the problem they were trying to solve before, using XMPP for everything.

Nowadays, my friends at Google (who have been slowly crawling up the hierarchy to the managerial layer) use WhatsApp. That pretty much says everything.

So, if not even Google is able to 'beat the standards' by creating their own... why should anyone else succeed? Imagine if Google hadn't dropped XMPP so early. Today, we'd have the whole world on a single XMPP-compatible platform — with a few exceptions, of course, fighting for relevance. The _real_ battle would be on the features presented by each company's _client_ software — not on the underlying protocols. Those, like the Web, would run on top of standards.

Alas, 'tis was not to be, and therefore, we'll live in a fragmented Chat-O-sphere forever...

Anyway, in the Go world, the closest we got to ejabberd is [Jackal](https://github.com/ortuman/jackal) — the only reason I don't like it is because their developers lock me to PostgreSQL — it doesn't work with anything else (and for no good reason; I've been through their code and, except for the so-called 'modular' approach, there is nothing really preventing the database backend to be replaced — but that would require rewriting a lot of code on the assumption that the database layer is shielded from the layers above).

Tinode could very well become Jackal's closest competitor. All the core developers of Tinode needed to do is to add a XMPP-compatibility layer to it :-)

Then again, what do I know... all I need Jabber/XMPP for is to get a real-time chat going on phpBB forums, anyway... since phpBB3 includes Jabber/XMPP connectivity by default ;-)

**Comment by or-else** [comment]
> All the core developers of Tinode needed to do is to add a XMPP-compatibility layer to it :-)

We are not going to do it but you are welcome to contribute it.

**Comment by Neustradamus** [comment]
Jackal IM development has been stopped by this author.

And the good Go lib is:
- https://github.com/xmppo/go-xmpp

**Comment by GwynethLlewelyn** [comment]
> Jackal IM development has been stopped by this author.

Ah, thanks for letting me know. Actually, when I posted my own comment, Jackal IM was still being developed. Not actively, but not 'stopped' yet.

> And the good Go lib is:
> 
> * https://github.com/xmppo/go-xmpp

Oh! Thank you for the link! And it has code by the legendary Yasuhiro Matsumoto! This means that the project is in the best of hands.

One wonders how it compares/contrasts to https://github.com/FluuxIO/go-xmpp — which has been mentioned by @stevenroose — since it's _also_ being (actively) maintained. Hmm.

**Comment by Neustradamus** [comment]
If there is a missing XEP support, please create a comment in the specified repository to request it.

**Comment by or-else** [comment]
Please take this conversation elsewhere.
