### ISSUE TITLE
discovery tags

### ISSUE THREAD

**Issue by bogdantarasenkozp** [tinode/chat#56]
Hi guys,this is the most awesome open-source product that i saw, but i found a bug, i cant create more then 3 tags on 'acc' it responds with error 500

**Comment by or-else** [comment]
Thanks for the bug report. Could you please provide a bit more details? Specifically, if you are using the web client, open the browser console and copy the log of commands.

**Comment by or-else** [comment]
Actually, never mind. I can reproduce it. Thanks!

**Comment by bogdantarasenkozp** [comment]
![2017-12-20 02-30-57](https://user-images.githubusercontent.com/20387183/34185444-fc26e348-e52d-11e7-804d-63a74a5aea85.png)

**Comment by bogdantarasenkozp** [comment]
Thank you for reply)
the error 500 appears when i add more then 3 tags, if there are 1, 2 or 3 tags everything works good

**Comment by or-else** [comment]
I was wrong, this is something else. Since you are running your local server, could you also show the server logs when this happens? 

Are you using the stock `config` file? If you've changed it, can you share what you have for `"indexable_tags": ["foo",...],` in the config?

I suspect it may not actually be a bug but rather an unclear error message. Indexable tags are supposed to be unique. You may be  trying to add a non-unique tag. I.e. `gender:female` is likely to be non-unique. 

If you want to add extra account info, add it to the `public` or `private` fields.

**Comment by or-else** [comment]
I've updated error handling for duplicate tags: https://github.com/tinode/chat/commit/91ab467d55963e03f7c6b2b4c194d470c46c1aa4
I'm certain that you will start receiving error 409 instead of 500.

**Comment by bogdantarasenkozp** [comment]
yeah,you absolutly right, thank you for responce
