### ISSUE TITLE
[question] groups of 16?

### ISSUE THREAD

**Issue by faddat** [tinode/chat#6]
Do you plan to increase the possible group size, or is it going to stay at 16?  If so, why?

Thanks

**Comment by or-else** [comment]
Well, technically the limit is not currently enforced. 

I chose 16 by conducting a quick poll among my colleagues asking what's the largest group chat they've been to. The group chat is defined as a conversation where people all know each other as opposite to an open chat room amongst strangers. The maximum answer was 8 so I doubled it.

There has to be a reasonable limit on the number of people in one group chat where access is managed individually. It cold be high, maybe a few hundred, but not unlimited because of overhead and limited usability of such chats. I could potentially move the limit to the config file.

Large open chats are expected to be handled differently.
