### ISSUE TITLE
Revise how `contacts()` works

### ISSUE THREAD

**Issue by j4hangir** [tinode/chat#602]
At the moment it is not possible to retrieve a list of all contacts directly, one has to make a call to `.contacts()` and provide a `CB` to retrieve them one by one:

```js
contacts: {
    value: function(callback, context) {
      const cb = (callback || this.onMetaSub);
      if (cb) {
        for (let idx in this._contacts) {
          cb.call(context, this._contacts[idx], idx, this._contacts);
        }
      }
    },
    enumerable: true,
    configurable: true,
    writable: true
  }
```

Getting the list of all contacts at once is sometimes very handy and accessing the private property doesn't sound like a good idea.

I suggest either a `getContacts()` is set for the `_contacts`, possibly with a promise, or another way is devised for retrieving the list.

**Comment by or-else** [comment]
I did it this way because I wanted it to be read-only. It was too difficult to make this property read-only using JS so I resorted to using the iterator. I don't mind exposing the value but please don't call it `getXXX` because `getXXX` here is used to fetch data from the server, i.e. implies a network call. And if you can, then make it read-only.

**Comment by or-else** [comment]
Please send a pull request.

**Comment by or-else** [comment]
Against `next`.

**Comment by SatoshiNakamotogmx** [comment]
Do I need to start pulling requests for my project?

On Jan 14, 2021 11:05 AM, "Gene" <notifications@github.com> wrote:

Against next.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tinode/chat/issues/602#issuecomment-760405684>, or
unsubscribe

**Comment by or-else** [comment]
@SatoshiNakamotogmx Are you asking about what a pull request is?
https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-requests

It's only needed if you would like to make changes to the code which you want to be incorporated in the upstream.

**Comment by j4hangir** [comment]
> Please send a pull request.

Think this will do: https://github.com/tinode/tinode-js/pull/42

**Comment by j4hangir** [comment]
Either way I don't care anymore, I'll work around it.


This process has been too tedious and bureaucratic.

**Comment by or-else** [comment]
Thanks
