### ISSUE TITLE
large files support

### ISSUE THREAD

**Issue by pcgpcgpcg** [tinode/chat#62]
hi,rethinkdb not support binary file over a MB. if a video 's size exceed. How to handle it?

**Comment by or-else** [comment]
Hi,

I would suggest to upload the video to a separate storage system, like Amazon S3, and then send a link to the uploaded video. The message format (`drafty`) is quite flexible at what it can carry. It can be easily extended for new data types.

**Comment by pcgpcgpcg** [comment]
good idea! There's two way to solve it.  
1.modify the rethinkdb to mongdb+gridFS    gridFS support large files
2.use a separate storage system
i don't know which one is easiest?

**Comment by or-else** [comment]
I don't think it's a good idea to embed large objects into messages:

* If the large object is sent in-band, then it will also be received in-band. Imagine someone is fetching messages from the server and it takes 10 minutes just to get the unread messages because one message is very large. Or someone sends you a video and you have no choice but to use mobile data to download a 100MB video because it's embedded in the message. I think it's a better user experience if large media downloads are separate from receiving messages and if the user can control when and what to download. I think WeChat & WhatsApp & Telegram got it right - you get a preview in-band and then choose to download the whole thing out-of-band.

* Overall database operations over a dataset with large objects embedded will be slower compare to the same objects stored separately. For instance, you can store the messages on SSDs and large objects on spinning disks. If the objects are embedded, you have no such option. 

As for adding MongoDB as a storage option - i think it's a good idea.

**Comment by pcgpcgpcg** [comment]
Thank you very much! We decide to try   fastFDS, later will share our experience on it

**Comment by or-else** [comment]
Any update on this? Thanks!
